### PR TITLE
python command is added in contributing.md

### PR DESCRIPTION
**Pull request by vishnu-31**
In the CONTRIBUTING.md

I found that  while running the program, the `python` command was missing. So, I added it.

image

### CODE REVIEW

**Comment by suraj-singh12** [comment]
The tool preferably uses python3. So just update the python command to python3, and your PR is good to go.

**Comment by suraj-singh12** [comment]
The tool works without the python command, that's why we have done this:
`chmod +x SearchEverywhere.py`     
The above command makes the SearchEverywhere.py an executable file, so it can run without requiring to call python interpreter explicitly.

Did you face any problem while running this: 
`./SearchEverywhere.py - heading`

If yes, are you using multiple python installations?

**Comment by vishnu-31** [comment]
So, I checked it again. And it is needed.
Here's the output of the current command:
pullrequest_error_proof

**Comment by suraj-singh12** [comment]
Ohh!, it is because of the line endings being CRLF instead of LF.
It happened accidentally when I had made a  commit using Windows.

Writing ```python``` at the beginning of the command would make it a bit annoying when you do testing.
You can just change the line endings to LF of the SearchEverywhere file.
That's the best solution.

**Comment by suraj-singh12** [comment]
This is fixed in #11 
I am closing the PR. 
As this was an alternatively valid PR, so I will be marking it as accepted.

**Pull request closed without merging**
